# Generated by Django 2.0.7 on 2018-07-25 06:09

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.UUID('39973219-e579-4f06-b24a-5ae0566d7bf0'))),
                ('sequence', models.IntegerField()),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
